### PR TITLE
Correct highlighting for aarch64 integer and neon registers

### PR DESCRIPTION
**Pull request by RSDuck**

### CODE REVIEW

**Comment by dan-c-underwood** [comment]
Thanks for this, I’m away until the start of January but will review when I’m back!

**Comment by RSDuck** [comment]
ok till then, thank you for the info

**Comment by RSDuck** [comment]
hello, I hope I don't bother you, but I want to ask you if you can review pull request?

**Comment by dan-c-underwood** [comment]
Apologies for the delay on this! I'll publish a new version shortly. Thanks for the contribution 😄

**Pull request merged**
